const express = require("express");
const router = express.Router();
const ConfiguracaoAlertaController = require("../controllers-mongodb/configuracaoAlertaController");
const authMiddleware = require("../middleware/auth-mongodb");
router.get("/dispositivo/:dispositivoId",ConfiguracaoAlertaController.porDispositivo);
router.post("/padrao/:tipo", ConfiguracaoAlertaController.criarPadrao);
router.post("/", ConfiguracaoAlertaController.criar);
router.get("/", ConfiguracaoAlertaController.listar);
router.get("/:id", ConfiguracaoAlertaController.buscar);
router.put("/:id", ConfiguracaoAlertaController.atualizar);
router.delete("/:id", ConfiguracaoAlertaController.deletar);
module.exports = router;